#!/usr/bin/env python3
"""Build kubernetes/prometheusrule-federation.yaml.

The cluster Prometheus needs the same node recording rules as the VM
environments (so the global alerts work the same way for k8s nodes) plus
some Kubernetes-only ones. Rather than keep two copies in sync by hand,
this script assembles the PrometheusRule from the source files.

    python3 scripts/build-k8s-rules.py          # write the file
    python3 scripts/build-k8s-rules.py --check  # fail if it's out of date (CI)
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SOURCES = [
    (ROOT / "prometheus/rules/recording.yml", {"node.recording"}),
    (ROOT / "kubernetes/rules/k8s-recording.yml", None),  # all groups
]
OUTPUT = ROOT / "kubernetes/prometheusrule-federation.yaml"

HEADER = """\
# GENERATED by scripts/build-k8s-rules.py - edit the source rule files instead.
# kubectl apply -n monitoring -f kubernetes/prometheusrule-federation.yaml
"""


class LiteralDumper(yaml.SafeDumper):
    pass


def _str(dumper, value):
    style = "|" if "\n" in value else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)


LiteralDumper.add_representer(str, _str)


def build() -> str:
    groups = []
    for path, wanted in SOURCES:
        for group in yaml.safe_load(path.read_text())["groups"]:
            if wanted is None or group["name"] in wanted:
                groups.append(group)

    manifest = {
        "apiVersion": "monitoring.coreos.com/v1",
        "kind": "PrometheusRule",
        "metadata": {
            "name": "federation-recording-rules",
            "namespace": "monitoring",
            "labels": {"app.kubernetes.io/part-of": "prometheus-federation-monitoring"},
        },
        "spec": {"groups": groups},
    }
    body = yaml.dump(manifest, Dumper=LiteralDumper, sort_keys=False, width=120)
    return HEADER + body


def main() -> int:
    content = build()
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date - run scripts/build-k8s-rules.py")
            return 1
        print("k8s rules up to date")
        return 0
    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
